from pathlib import Path

p = Path('app/src/main/java/com/yagay/ListCleaner/xposed/ListCleanerModule.kt')
s = p.read_text()
old = '''        return runCatching {\n            intentField.isAccessible = true\n            resolveField.isAccessible = true\n            activityField.isAccessible = true\n            intentField.set(request, chooser)\n            resolveField.set(request, resolved)\n            activityField.set(request, resolved.activityInfo)\n            resolvedTypeField?.let { it.isAccessible = true; it.set(request, null) }\n            componentSpecifiedField?.let { it.isAccessible = true; it.setBoolean(request, false) }\n            diagnostic(\n                \"CHOOSER_SYSTEM_REDIRECT_APPLIED uid=${view.uid} caller=${view.callerPackage} \" +\n                    \"from=${component.flattenToShortString()} kind=${template.kind} targetAction=${payload.action} \" +\n                    \"mime=${payload.type} uri=${payloadHasUri(payload)} resolver=${resolved.activityInfo?.packageName}/${resolved.activityInfo?.name}\"\n            )\n            true\n        }.getOrElse {\n'''
new = '''        return runCatching {\n            val resolverInfo = requireNotNull(resolved.activityInfo)\n            val resolverComponent = ComponentName(resolverInfo.packageName, resolverInfo.name)\n            // OxygenOS resolves ACTION_CHOOSER to a launcher/trampoline, but executeRequest may\n            // re-resolve an implicit chooser later and return START_INTENT_NOT_RESOLVED (-91).\n            // Pin the already-resolved platform component and keep both request Intent slots in sync.\n            chooser.component = resolverComponent\n            intentField.isAccessible = true\n            resolveField.isAccessible = true\n            activityField.isAccessible = true\n            intentField.set(request, chooser)\n            allInstanceFields(request.javaClass)\n                .firstOrNull { it.name == \"ephemeralIntent\" && Intent::class.java.isAssignableFrom(it.type) }\n                ?.let { field -> field.isAccessible = true; field.set(request, Intent(chooser)) }\n            resolveField.set(request, resolved)\n            activityField.set(request, resolverInfo)\n            resolvedTypeField?.let { it.isAccessible = true; it.set(request, null) }\n            componentSpecifiedField?.let { it.isAccessible = true; it.setBoolean(request, true) }\n            diagnostic(\n                \"CHOOSER_SYSTEM_REDIRECT_APPLIED uid=${view.uid} caller=${view.callerPackage} \" +\n                    \"from=${component.flattenToShortString()} kind=${template.kind} targetAction=${payload.action} \" +\n                    \"mime=${payload.type} uri=${payloadHasUri(payload)} resolver=${resolverComponent.flattenToShortString()} explicit=true\"\n            )\n            true\n        }.getOrElse {\n'''
if old not in s:
    raise SystemExit('redirect block not found')
s=s.replace(old,new,1)
p.write_text(s)
print('patched', p)
